# Generated by Django 4.1.5 on 2025-11-04 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name="To'liq nomi")),
                ('short_name', models.CharField(max_length=100, verbose_name='Qisqacha nomi')),
                ('organization_type', models.CharField(choices=[('SCHOOL', 'Maktab'), ('HOSPITAL', 'Kasalxona'), ('GOVERNMENT', 'Davlat idorasi'), ('UNIVERSITY', 'Universitet'), ('OTHER', 'Boshqa')], max_length=20, verbose_name='Tashkilot turi')),
                ('inn', models.CharField(max_length=20, unique=True, verbose_name='INN')),
                ('oked', models.CharField(blank=True, max_length=20, null=True, verbose_name='OKED')),
                ('mfo', models.CharField(blank=True, max_length=10, null=True, verbose_name='MFO')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hisob raqam')),
                ('legal_address', models.TextField(verbose_name='Yuridik manzil')),
                ('actual_address', models.TextField(blank=True, null=True, verbose_name='Haqiqiy manzil')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('director_name', models.CharField(max_length=256, verbose_name='Direktor F.I.O.')),
                ('director_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Direktor telefoni')),
                ('responsible_person', models.CharField(max_length=256, verbose_name="Mas'ul shaxs F.I.O.")),
                ('responsible_position', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mas'ul shaxs lavozimi")),
                ('responsible_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name="Mas'ul shaxs telefoni")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'db_table': 'Organizations',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Shartnoma raqami')),
                ('contract_date', models.DateField(verbose_name='Shartnoma sanasi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Umumiy summa')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name="To'lov shartlari")),
                ('delivery_terms', models.TextField(blank=True, null=True, verbose_name='Yetkazib berish shartlari')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('EXPIRED', 'Muddati tugagan'), ('TERMINATED', 'Bekor qilingan')], default='ACTIVE', max_length=20, verbose_name='Holati')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Shartnoma fayli')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan xodim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
                'db_table': 'Contracts',
                'ordering': ['-contract_date'],
            },
        ),
    ]
