# Generated by Django 4.1.5 on 2025-11-04 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_category_options_alter_product_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Yuk xati raqami')),
                ('date', models.DateField(verbose_name='Sana')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Oraliq jami')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy summa')),
                ('payment_status', models.CharField(choices=[('UNPAID', "To'lanmagan"), ('PARTIAL', "Qisman to'langan"), ('PAID', "To'langan")], default='UNPAID', max_length=20, verbose_name="To'lov holati")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan summa")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='organizations.contract', verbose_name='Shartnoma')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan xodim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Yuk xati',
                'verbose_name_plural': 'Yuk xatlari',
                'db_table': 'DeliveryNotes',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name="To'lov sanasi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('payment_document', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov hujjati")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan xodim')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.deliverynote', verbose_name='Yuk xati')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'db_table': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256, verbose_name='Mahsulot nomi')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seriya raqami')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narxi')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='organizations.deliverynote', verbose_name='Yuk xati')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Yuk xati tafsiloti',
                'verbose_name_plural': 'Yuk xati tafsilotlari',
                'db_table': 'DeliveryNoteDetails',
            },
        ),
    ]
