# Generated by Django 4.1.5 on 2025-11-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_category_options_alter_product_options_and_more'),
        ('organizations', '0002_deliverynote_payment_deliverynotedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barcode')),
                ('internal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ichki kod')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan xodim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Barcode',
                'verbose_name_plural': "Barcode'lar",
                'db_table': 'ProductBarcodes',
                'ordering': ['-created_date'],
            },
        ),
    ]
