# Generated by Django 4.1.5 on 2025-11-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_productbarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_organizations', models.BooleanField(default=False, verbose_name="Tashkilotlarni ko'rish")),
                ('can_add_organizations', models.BooleanField(default=False, verbose_name="Tashkilot qo'shish")),
                ('can_edit_organizations', models.BooleanField(default=False, verbose_name='Tashkilotni tahrirlash')),
                ('can_delete_organizations', models.BooleanField(default=False, verbose_name="Tashkilotni o'chirish")),
                ('can_view_contracts', models.BooleanField(default=False, verbose_name="Shartnomalarni ko'rish")),
                ('can_add_contracts', models.BooleanField(default=False, verbose_name="Shartnoma qo'shish")),
                ('can_edit_contracts', models.BooleanField(default=False, verbose_name='Shartnomani tahrirlash')),
                ('can_delete_contracts', models.BooleanField(default=False, verbose_name="Shartnomani o'chirish")),
                ('can_view_delivery_notes', models.BooleanField(default=False, verbose_name="Yuk xatlarini ko'rish")),
                ('can_add_delivery_notes', models.BooleanField(default=False, verbose_name='Yuk xati yaratish')),
                ('can_delete_delivery_notes', models.BooleanField(default=False, verbose_name="Yuk xatini o'chirish")),
                ('can_print_delivery_notes', models.BooleanField(default=False, verbose_name='Yuk xatini chop etish')),
                ('can_view_products', models.BooleanField(default=True, verbose_name="Mahsulotlarni ko'rish")),
                ('can_add_products', models.BooleanField(default=False, verbose_name="Mahsulot qo'shish")),
                ('can_edit_products', models.BooleanField(default=False, verbose_name='Mahsulotni tahrirlash')),
                ('can_delete_products', models.BooleanField(default=False, verbose_name="Mahsulotni o'chirish")),
                ('can_edit_prices', models.BooleanField(default=False, verbose_name="Narxlarni o'zgartirish")),
                ('can_view_payments', models.BooleanField(default=False, verbose_name="To'lovlarni ko'rish")),
                ('can_add_payments', models.BooleanField(default=False, verbose_name="To'lov qo'shish")),
                ('can_delete_payments', models.BooleanField(default=False, verbose_name="To'lovni o'chirish")),
                ('can_view_reports', models.BooleanField(default=False, verbose_name="Hisobotlarni ko'rish")),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='Hisobotlarni eksport qilish')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Xodim ruxsati',
                'verbose_name_plural': 'Xodimlar ruxsatlari',
                'db_table': 'EmployeePermissions',
            },
        ),
    ]
