# Generated by Django 4.2.26 on 2026-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_employeepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_add_customers',
            field=models.BooleanField(default=False, verbose_name="Mijoz qo'shish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_add_debt',
            field=models.BooleanField(default=False, verbose_name="Qarz qo'shish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_add_debt_payments',
            field=models.BooleanField(default=False, verbose_name="Qarz to'lovi qilish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_add_sales',
            field=models.BooleanField(default=False, verbose_name='Savdo qilish'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_delete_customers',
            field=models.BooleanField(default=False, verbose_name="Mijozni o'chirish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_delete_debt',
            field=models.BooleanField(default=False, verbose_name="Qarzni o'chirish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_delete_sales',
            field=models.BooleanField(default=False, verbose_name="Savdoni o'chirish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_customers',
            field=models.BooleanField(default=False, verbose_name='Mijozni tahrirlash'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_debt',
            field=models.BooleanField(default=False, verbose_name='Qarzni tahrirlash'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_sales',
            field=models.BooleanField(default=False, verbose_name='Savdoni tahrirlash'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_manage_barcodes',
            field=models.BooleanField(default=False, verbose_name='Barcodeni boshqarish'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_receive_warehouse',
            field=models.BooleanField(default=False, verbose_name='Omborga qabul qilish'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_customers',
            field=models.BooleanField(default=True, verbose_name="Mijozlarni ko'rish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_debt',
            field=models.BooleanField(default=False, verbose_name="Qarz daftarini ko'rish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_pos',
            field=models.BooleanField(default=True, verbose_name="POS panelini ko'rish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_sales',
            field=models.BooleanField(default=True, verbose_name="Savdlarni ko'rish"),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_warehouse',
            field=models.BooleanField(default=True, verbose_name="Omborni ko'rish"),
        ),
    ]
