# Generated by Django 4.2.26 on 2026-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Kalit')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('value_type', models.CharField(choices=[('STRING', 'Matn'), ('INTEGER', 'Butun son'), ('FLOAT', "O'nlik son"), ('BOOLEAN', "Ha/Yo'q"), ('JSON', 'JSON')], max_length=20, verbose_name='Qiymat turi')),
                ('value', models.TextField(verbose_name='Qiymat')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='Default qiymat')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Tahrirlash mumkin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
                'db_table': 'SystemSettings',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100, verbose_name='Ilova nomi')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('verbose_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Model nomi (birlik)')),
                ('verbose_name_plural', models.CharField(blank=True, max_length=256, null=True, verbose_name="Model nomi (ko'plik)")),
                ('list_per_page', models.IntegerField(default=20, verbose_name='Sahifadagi yozuvlar soni')),
                ('list_display_fields', models.TextField(blank=True, null=True, verbose_name="Ro'yxatda ko'rsatiladigan maydonlar (vergul bilan)")),
                ('search_fields', models.TextField(blank=True, null=True, verbose_name='Qidiruv maydonlari (vergul bilan)')),
                ('list_filter_fields', models.TextField(blank=True, null=True, verbose_name='Filter maydonlari (vergul bilan)')),
                ('ordering_fields', models.TextField(blank=True, null=True, verbose_name='Saralash maydonlari (vergul bilan)')),
                ('readonly_fields', models.TextField(blank=True, null=True, verbose_name="Faqat o'qish uchun maydonlar (vergul bilan)")),
                ('allow_add', models.BooleanField(default=True, verbose_name="Qo'shish ruxsati")),
                ('allow_edit', models.BooleanField(default=True, verbose_name='Tahrirlash ruxsati')),
                ('allow_delete', models.BooleanField(default=True, verbose_name="O'chirish ruxsati")),
                ('allow_export', models.BooleanField(default=True, verbose_name='Eksport ruxsati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Model sozlamasi',
                'verbose_name_plural': 'Model sozlamalari',
                'db_table': 'ModelSettings',
                'ordering': ['app_label', 'model_name'],
                'unique_together': {('app_label', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='FieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100, verbose_name='Ilova nomi')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('field_name', models.CharField(max_length=100, verbose_name='Maydon nomi')),
                ('field_type', models.CharField(choices=[('CharField', 'Matn'), ('TextField', 'Katta matn'), ('IntegerField', 'Butun son'), ('FloatField', "O'nlik son"), ('DecimalField', 'Pul'), ('BooleanField', "Ha/Yo'q"), ('DateField', 'Sana'), ('DateTimeField', 'Sana va vaqt'), ('EmailField', 'Email'), ('ForeignKey', "Bog'lanish"), ('ImageField', 'Rasm'), ('FileField', 'Fayl')], max_length=50, verbose_name='Maydon turi')),
                ('verbose_name', models.CharField(blank=True, max_length=256, null=True, verbose_name="Ko'rinadigan nom")),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='Yordam matni')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy maydon')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsin")),
                ('is_editable', models.BooleanField(default=True, verbose_name='Tahrirlash mumkin')),
                ('show_in_list', models.BooleanField(default=True, verbose_name="Ro'yxatda ko'rsatish")),
                ('show_in_form', models.BooleanField(default=True, verbose_name="Formada ko'rsatish")),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='Default qiymat')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='Minimal uzunlik')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='Maksimal uzunlik')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Minimal qiymat')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Maksimal qiymat')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Maydon sozlamasi',
                'verbose_name_plural': 'Maydon sozlamalari',
                'db_table': 'FieldSettings',
                'ordering': ['app_label', 'model_name', 'order', 'field_name'],
                'unique_together': {('app_label', 'model_name', 'field_name')},
            },
        ),
    ]
