# Generated by Django 4.2.26 on 2026-01-21 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_employeepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_or_service', models.CharField(max_length=200, verbose_name='Mahsulot yoki bajarilgan ish')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan summa")),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qolgan qarz')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('payment_status', models.CharField(choices=[('UNPAID', "To'lanmagan"), ('PARTIAL', 'Qisman'), ('PAID', "To'liq")], default='UNPAID', max_length=10, verbose_name="To'lov holati")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan xodim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_records', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Qarz yozuvi',
                'verbose_name_plural': 'Qarz yozuvlari',
                'db_table': 'DebtRecords',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name="To'lov izohi")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan xodim')),
                ('debt_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debt.debtrecord', verbose_name='Qarz yozuvi')),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
                'db_table': 'DebtPayments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['organization'], name='DebtRecords_organiz_917cff_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['payment_status'], name='DebtRecords_payment_dc5ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['date'], name='DebtRecords_date_e8906f_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['due_date'], name='DebtRecords_due_dat_ffbb5d_idx'),
        ),
    ]
