# Generated by Django 4.1.5 on 2026-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtrecord',
            name='product_or_service',
            field=models.TextField(verbose_name='Mahsulot yoki bajarilgan ish'),
        ),
    ]
