# Generated by Django 4.1.5 on 2025-11-04 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_category_options_alter_product_options_and_more'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('sales', '0003_rename_venta_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Savdo', 'verbose_name_plural': 'Savdolar'},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'Savdo tafsiloti', 'verbose_name_plural': 'Savdo tafsilotlari'},
        ),
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_change',
            field=models.FloatField(default=0, verbose_name='Qaytim'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_payed',
            field=models.FloatField(default=0, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='grand_total',
            field=models.FloatField(default=0, verbose_name='Umumiy jami'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sub_total',
            field=models.FloatField(default=0, verbose_name='Oraliq jami'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_amount',
            field=models.FloatField(default=0, verbose_name='Soliq miqdori'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_percentage',
            field=models.FloatField(default=0, verbose_name='Soliq foizi'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='price',
            field=models.FloatField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sale', verbose_name='Savdo'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='total_detail',
            field=models.FloatField(verbose_name='Jami'),
        ),
    ]
