# Generated by Django 4.1.5 on 2026-02-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('products', '0008_alter_product_barcode'),
        ('sales', '0004_alter_sale_options_alter_saledetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale', verbose_name='Savdo'),
        ),
    ]
