# Generated by Django 4.1.5 on 2026-02-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_employeepermission_can_add_customers_and_more'),
        ('sales', '0005_alter_sale_customer_alter_sale_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', help_text="Agar tashkilotga savdo bo'lsa tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Tashkilot'),
        ),
    ]
