# Generated by Django 4.1.5 on 2026-02-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('sales', '0006_sale_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer', help_text="Mijoz yoki Tashkilotdan biri bo'lishi kerak", null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Mijoz'),
        ),
    ]
