# Generated by Django 4.2.26 on 2026-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Shtrix-kod'),
        ),
    ]
